### PR TITLE
Restructured OptionalPCB and exposed to REST

### PR DESCRIPTION
**Pull request by CurlyMoo**

### CODE REVIEW

**Comment by CurlyMoo** [comment]
With the acceptance of my previous PR some bogus topics have appeared:
```
panasonic_heat_pump/sdc/Holi1- h
panasonic_heat_pump/s11 pu
panasonic_heat_pu11 /1w
panasonic_heat_p1* dc
panasonic_heat_pum1- s
pa16 ur
```

I haven't got the time to debug it but maybe you've got an idea.

**Comment by IgorYbema** [comment]
Code is wrong. You need to set global variable optionalPCBQuery to have the new data and not send the default optionalPCBQuery  value on each new data.
It is up to the main process to send the optionalPCBQuery then each 5 seconds.

**Comment by CurlyMoo** [comment]
No need to close the PR. Give me some a minute to fix it.

**Comment by CurlyMoo** [comment]
And fixed. Can you reopen the PR and again review it.

**Pull request closed without merging**
