### PR TITLE
Update decode.h

### PR DESCRIPTION
**Pull request by Grufti68**

### CODE REVIEW

**Review by IgorYbema — COMMENTED** [review]
Also line 38 needs to be modified (from 29 to 30).

**Comment by Grufti68** [comment]
I added it to Egyra's HeishaMon. is that enough ? otherwise I don't know what you mean

**Comment by IgorYbema** [comment]
You modified decode.h but you also need to change the amount of devices which is on line 38

**Comment by Grufti68** [comment]
I understand. I changed it at Ebyras

**Comment by IgorYbema** [comment]
Please combine your PR's to one PR. And choose where to publish, here or at mine. Not both.

**Pull request closed without merging**
