### PR TITLE
Replace millis() async delays by a single timerqueue

### PR DESCRIPTION
**Pull request by CurlyMoo**
This commit makes a start to get to a full async operation.
That means no or minimal blocking calls are made. A timerqueue
also makes it possible to implement timers inside the upcoming
rules.

The millis() method is pretty intertwined with some of the
functions of the current codebase. That means this rewrite
requires a more extensive review to check nothing is actually
broken.

Besides providing the original functionality just implemented
differently, this commit also add the improvement that the MQTT
and WiFi connection can be restored without having to reboot.

Another change is that the onS0Pulse interrupts now contains
more logic. I believe this adds such a marginal delay that
it doesn't effect normal operation.

The next step is to make the WiFiManager async.

----

This PR is the third of a series working towards implementing
rules.

### CODE REVIEW

**Comment by IgorYbema** [comment]
Code was mostly non blocking already but indeed some parts are.
I need to check this and there are some conflicts

**Comment by CurlyMoo** [comment]
This code was also done against an older version. Let me fix that first.

**Comment by IgorYbema** [comment]
Just had some time to check this again.
Ofcourse this PR currently breaks the code due to some major changes since the PR was published.
But I also now believe there is no reason for a task scheduler like this. The only real task that is able to be scheduled is the 5 seconds read timer. Any other timers are just for timeouts or pulse calculations.

I also don't understand why this is necessary for your future update for running your extra code. Then again, maybe we need a rewrite for that on a ESP32 because the current ESP8266 is probably too slow to run extra external code anyways. 

For now I am closing this PR. I will first publish a v2 heishamon binary first with the current code.

**Comment by CurlyMoo** [comment]
> But I also now believe there is no reason for a task scheduler like this.
> I also don't understand why this is necessary for your future update for running your extra code.

I explained that on slack. The rules system needs to be able to define an undefined number of unknown length timers to be fully usefull. The only way to encompas this is through a timerpool.

The second reason is the modularity and clearity of the codebase i did suggestions for earlier. And for which you asked me to keep doing suggestions. If you are going to implement a timerpool anyway, it's best to let all timers use the timerpool instead of using the same logic over and over again throughout your codebase. But indeed, for the current timeout's this is not strictly necessary.

>  Then again, maybe we need a rewrite for that on a ESP32 because the current ESP8266 is probably too slow to run extra external code anyways.

My tests showed it works fine on a ESP8266.

> For now I am closing this PR. I will first publish a v2 heishamon binary first with the current code.

There is no problem keeping PR's open for future purposes.

**Comment by CurlyMoo** [comment]
Where you convinced by my explanation or do you have another idea how to implement the same functionality. It's mandatory to get the rules system to fully replace my current external implementation.

**Comment by IgorYbema** [comment]
A timerpool is not something special. Itself is also called from the mainloop and just calls callback functions as far as I can tell.
It is not necessary to change the current working code to such a timerpool.
Currently all functions are already non-blocking (that is necessary for a good working heishamon already) so adding the timerpool to the mainloop just for running the external code is a good way to start off I think.

The only blocking stuff is TCP/IP in the LWP code itself which can block to due network timeouts. But we can't change that. I notice that when a bad wifi is trying to connect to a mqtt server. That is all library's outside of my scope.

If there was a way to have a timerpool which could initiate interrupts, that would be a total different ball game and that would be totally different than the current 'run everything from the main loop' design.

**Comment by IgorYbema** [comment]
Yes and for now only use it for the new external code. Later we could add some other internal routines if it seems necessary.

**Pull request closed without merging**
