### PR TITLE
Additional Zone2 topics + setDHWHeater and working platfromio

### PR DESCRIPTION
**Pull request by geduxas**
Additional topics for 2 Zones, 
Confirmed valve mixing timing, and zone pump status.
Also add SetDHWHeater to allow control heater for DHW

Fixed platfromio.ini to compile for heishamon boards.

### CODE REVIEW

**Comment by IgorYbema** [comment]
What is the 'time' value in the mixing valve? What does it stand for? seconds?

**Comment by geduxas** [comment]
> What is the 'time' value in the mixing valve? What does it stand for? seconds?

First please don't add this yet :) i think i made some mistakes.. so please let me check for some time..

as for mixing valves i think i was too fast :) it was mentioned as seconds in decode document.. and in graph looks like that.. now i am not thinking that it's second's. Just in valve closed position, it's set to value of 200, and while opening valve it ticks for -1 in ~5sec (read interval) it's also corresponding to pulsing times for valve.. so it could also lead to percentage of opened valve.. and stops when it reaches desired temperature.. if temperature is too high, it's going upward.. 

But there is downside, if valve is opened till end, but target temperature is not reached, values are going to zero...

Screenshot_2023-11-08-23-18-41-81_40deb401b9ffe8e1df2f1cc5ba480b12


As for heater control logic i messed up.. I'll try to fix it and test tomorrow.

**Comment by MiG-41** [comment]
In service cloud it is represented like here:
image

So not sure if we want invent circle from beginning...

**Comment by IgorYbema** [comment]
> In service cloud it is represented like here: image
> 
> So not sure if we want invent circle from beginning...

But this still doesn't make sense. If we look at the optional pcb data: https://github.com/IgorYbema/HeishaMon/blob/main/OptionalPCB.md#answerconfirmation-from-hp-to-optional-pcb

The mixing valve is asked to open (+), to close (-), or to do nothing there.

So this byte in the main pcb where we are looking at now can't be 'seconds'. Or at least, I can't understand how a mixing valve and seconds are connected to each other.

From the description I now understand that 200 = valve closed and 0 = valve opened and everything in between is in halve position somewhere. So could wel be a closed percentage divided by 2.

**Comment by IgorYbema** [comment]
Thinking about this, it can't be true also.
If you have 1 decimal steps eachs 5 seconds, it can take 200*5 (1000) seconds before the valve completly opens. But that just depends on the type of valve. So it is more something like percentage relative to the desired temperatue.

**Comment by geduxas** [comment]
It could be time counter which show's how long valve was has open/close command to reach it's temperature point. 
But behaves more like open/closed level.. but it will not match in any way..

**Comment by MiG-41** [comment]
Now from values 0x01 for both , set 0x11 and 0xF1  , so i got in service cloud values 16.00sec and 240.00sec , so DEC-1 is also ok.
image

**Comment by geduxas** [comment]
nice @MiG-41 .. so 0x10 =16s, and 0xF0=240s ? i am also doubt a little bit.. why opening goes to downside.. while closing goes upward ? :D

**Comment by geduxas** [comment]
Here is what type of mixing valve recommended from Panasonic

image

operating time 30-120s

**Comment by MiG-41** [comment]
It is not open and close , they are separate values for zone 1 and zone 2 ( valve 1 and valve 2 ) , in description "Zone 2" probably is confusing...

**Comment by geduxas** [comment]
ups i messed everything again.. 
so fully closed and not operating heatpump will set to value 0x01 (0-closed)

here is graph from start, and system was cooled down:

image

so valve goes from 0x01 (0 closed) to 0xC9 (200)

**Comment by geduxas** [comment]
And currently installed valve which i have, operating time 70s.

**Comment by IgorYbema** [comment]
I think it is just a relative open (200) to close (0) position for internal logic. 2000 = 1000 seconds and there is no valve which takes longer than 1000 seconds to open but it can take longer for the temperature to reach the setpoint so it keeps asking to open the valve more (even if it is already fully open) so it will reach 200 always. Then when it notices the setpoint is reached it starts closing and opening (see the ripple). 

So it is an internal value for approx. the valve open state but it doesn't mean that 50% is the same as 100 decimal.

**Comment by MiG-41** [comment]
For me it is predicted time till valve will close.... Ofcourse this prediction is  updated , so sometimes it starting decreasing , and then "pulled up" to max , and so on .

**Pull request closed without merging**
