### PR TITLE
Expose K&L topics to rules

### PR DESCRIPTION
**Pull request by CurlyMoo**

### CODE REVIEW

**Comment by IgorYbema** [comment]
Maybe I am blind but can't find the actOptData which was missing before also.

**Comment by CurlyMoo** [comment]
> Maybe I am blind but can't find the actOptData which was missing before also.

True, where should actOptData be placed?

**Comment by IgorYbema** [comment]
just like the TOP and XTOP, also check for OPT (actOptData and optTopics[])

**Comment by CurlyMoo** [comment]
That's what i'm doing here:
https://github.com/IgorYbema/HeishaMon/pull/127/files#diff-01e611e223b74b3014fcb8ea94fa38cb3fcb14850967c93186fc5dab1e1d1910R242-R252

here:
https://github.com/IgorYbema/HeishaMon/blob/c52eb183c34c656034affd417b5bbb5727a99c54/HeishaMon/rules.cpp#L242-L254

and here:
https://github.com/IgorYbema/HeishaMon/blob/c52eb183c34c656034affd417b5bbb5727a99c54/HeishaMon/rules.cpp#L1110-L1118

Is that not correct? The other variants of `*OptData` is never checked.

**Comment by IgorYbema** [comment]
No those are optionalCommands (so actions towards heishamon). Not the read data (like pump state for 2nd zone etc).

**Pull request merged**
