### PR TITLE
Generic timerqueue addition

### PR DESCRIPTION
**Pull request by CurlyMoo**

### CODE REVIEW

**Comment by IgorYbema** [comment]
timerqueue.cpp:135:35: error: 'REALLOC' was not declared in this scope
timerqueue.cpp:136:9: error: 'OUT_OF_MEMORY' was not declared in this scope
timerqueue.cpp:144:7: error: 'FREE' was not declared in this scope

Am i missing some #defines?

**Comment by CurlyMoo** [comment]
Just replace `REALLOC` with `realloc`, `OUT_OF_MEMORY` with another proper message, and `FREE` with `free`.

**Comment by CurlyMoo** [comment]
Are you gonna squash the PR this time?

**Comment by IgorYbema** [comment]
Don't know how to squash (in the github web interface or github windows tool).

**Comment by CurlyMoo** [comment]
It’s one of the merge options

**Pull request merged**
