### PR TITLE
Adding Pump_Flowrate_Mode for J series

### PR DESCRIPTION
**Pull request by CurlyMoo**
@IgorYbema Can you confirm it's as simpel as this?

### CODE REVIEW

**Comment by Heronimonimo** [comment]
How is this different from TOP95 Max_Pump_Duty?

**Comment by CurlyMoo** [comment]
This is the switch between delta T or Max pump speed for the J series. Max pump duty tells us what's that maximum is.

**Comment by CurlyMoo** [comment]
It could be that the naming should be different.

**Comment by Heronimonimo** [comment]
Ah. Maybe name it something like pump operation mode? With option Max_Duty and option DeltaT?

**Comment by CurlyMoo** [comment]
I've the idea the topics namings are copied from what the cloud has. I don't have a cloud so not sure if that's true.

**Comment by Heronimonimo** [comment]
Not so sure it's a cloud setting.

This is what the manual calls it:
Screenshot_20211219-184442_Dropbox

**Comment by Heronimonimo** [comment]
Which is a not so clever naming by Panasonic to be honest

**Comment by CurlyMoo** [comment]
`Pump_Flowrate` might be a good option.

**Comment by MiG-41** [comment]
I would call it Max Pumpflow , then when it is 1 ,HP tries to get max pump flow , when 0 use delta setting...

**Comment by IgorYbema** [comment]
Pump_Flowrate would be very confusing. I would suggest Pump_Flowrate_mode or Pump_mode

**Comment by Joeknx** [comment]
Is there a binary for the Pump_Flowrate_mode?
I tried 2.2.iy1, but there is no TOP 106
thx

**Comment by IgorYbema** [comment]
I stopped publishing dev binaries that way. You can look in the github actions for 'main' actions and get the binary from there.

https://github.com/IgorYbema/HeishaMon/actions

**Comment by Joeknx** [comment]
Ok, is it "safe" to use the latest main binary from there?

**Comment by IgorYbema** [comment]
Those are alpha versions. So not as safe as production versions like v1 and v2. Sometimes the alpha versions seem to brick the heishamon and then you need to recover it and know how to do that. There is no real reason currently to use them except if you really need that topic (which I don't think, because it is a setting which you don't often change).

**Comment by Joeknx** [comment]
You are right I don't know how to do that and don't really need this topic

**Pull request merged**
