### PR TITLE
Expose byte 22 to TOP111 and TOP112

### PR DESCRIPTION
**Pull request by geduxas**
For better implementation of thermostat component, we need to know which type of sensor is enabled in HeatPump.

https://github.com/kamaradclimber/heishamon-homeassistant/issues/57

### CODE REVIEW

**Comment by IgorYbema** [comment]
Just noticed this PR while I was adding TOP107 to TOP110. Can you change the code to use TOP111 and TOP112? I can then merge it with the 'addsensors' branch

**Comment by geduxas** [comment]
Ok, i think i left enough space :) just curious what will be in thous topics?

**Comment by Bucky2k** [comment]
It will be:

"Liquid_Type", //TOP107
  "Alt_External_Sensor", //TOP108
  "Anti_Freeze_Mode", //TOP109
  "Optional_PCB", //TOP110

**Comment by geduxas** [comment]
> It will be:
> 
> "Liquid_Type", //TOP107 "Alt_External_Sensor", //TOP108 "Anti_Freeze_Mode", //TOP109 "Optional_PCB", //TOP110

@Bucky2k thank's found it too :) 
@IgorYbema could you also add buffer tank delta? First didn't know what not exposed :D

**Comment by IgorYbema** [comment]
buffer tank delta is byte 59 as it seems. You are free to add that also :)

**Comment by IgorYbema** [comment]
Can you now fix the merge issue between the newtopics and your addons? I can do that also but much nicer if you do that :)

**Pull request merged**
