### PR TITLE
V3.5 release

### PR DESCRIPTION
**Pull request by IgorYbema**
Releasing v3.5 which includes support for the new model (with ESP32-S3 controller).

Also lot rules improvements, opentherm improvements and dallas sensors can have an alias in the web interface.

### CODE REVIEW

**Comment by MiG-41** [comment]
Hi @IgorYbema !
Good news is , that on this release MQTT reconnects is still 1 for whole 1 day :)
Two bad things :+1:
- after a while rules stopped working . I have rule with automaticly set Z1 and Z2 WaterTemp from dallas.... When i save rules again ,started working....
- i see in MQTT topic with value "{}" insted real value , that are: Z1_Heat_Curve_Target_High_Temp , Max_Pump_Duty, Solar_High_Limit

**Comment by IgorYbema** [comment]
Can you share your rules? And also for the second issue give the http://heishamon.local/json output?

**Comment by MiG-41** [comment]
Sure:
`on ds18b20#28aadd79a200035f then
	@SetZ1WaterTemp = ds18b20#28aadd79a200035f;
end

on ds18b20#289d3107d6013c3b then
	@SetZ2WaterTemp = ds18b20#289d3107d6013c3b;
end`

In json ,as well as on the webpage values are ok , it is only mqtt ....
image



`{"heatpump":[{"Topic":"TOP0","Name":"Heatpump_State","Value":0,"Description":"Off"},{"Topic":"TOP1","Name":"Pump_Flow","Value":0.13,"Description":"l/min"},{"Topic":"TOP2","Name":"Force_DHW_State","Value":0,"Description":"Disabled"},{"Topic":"TOP3","Name":"Quiet_Mode_Schedule","Value":0,"Description":"Disabled"},{"Topic":"TOP4","Name":"Operating_Mode_State","Value":3,"Description":"DHW"},{"Topic":"TOP5","Name":"Main_Inlet_Temp","Value":23.50,"Description":"&deg;C"},{"Topic":"TOP6","Name":"Main_Outlet_Temp","Value":22.50,"Description":"&deg;C"},{"Topic":"TOP7","Name":"Main_Target_Temp","Value":30,"Description":"&deg;C"},{"Topic":"TOP8","Name":"Compressor_Freq","Value":0,"Description":"Hz"},{"Topic":"TOP9","Name":"DHW_Target_Temp","Value":46,"Description":"&deg;C"},{"Topic":"TOP10","Name":"DHW_Temp","Value":36,"Description":"&deg;C"},{"Topic":"TOP11","Name":"Operations_Hours","Value":9678,"Description":"hours"},{"Topic":"TOP12","Name":"Operations_Counter","Value":4217,"Description":"count"},{"Topic":"TOP13","Name":"Main_Schedule_State","Value":0,"Description":"Disabled"},{"Topic":"TOP14","Name":"Outside_Temp","Value":13,"Description":"&deg;C"},{"Topic":"TOP15","Name":"Heat_Power_Production","Value":0,"Description":"Watt"},{"Topic":"TOP16","Name":"Heat_Power_Consumption","Value":0,"Description":"Watt"},{"Topic":"TOP17","Name":"Powerful_Mode_Time","Value":0,"Description":"Off"},{"Topic":"TOP18","Name":"Quiet_Mode_Level","Value":0,"Description":"Off"},{"Topic":"TOP19","Name":"Holiday_Mode_State","Value":0,"Description":"Off"},{"Topic":"TOP20","Name":"ThreeWay_Valve_State","Value":0,"Description":"Room"},{"Topic":"TOP21","Name":"Outside_Pipe_Temp","Value":12,"Description":"&deg;C"},{"Topic":"TOP22","Name":"DHW_Heat_Delta","Value":-5,"Description":"K"},{"Topic":"TOP23","Name":"Heat_Delta","Value":3,"Description":"K"},{"Topic":"TOP24","Name":"Cool_Delta","Value":5,"Description":"K"},{"Topic":"TOP25","Name":"DHW_Holiday_Shift_Temp","Value":-15,"Description":"K"},{"Topic":"TOP26","Name":"Defrosting_State","Value":0,"Description":"Disabled"},{"Topic":"TOP27","Name":"Z1_Heat_Request_Temp","Value":0,"Description":"&deg;C"},{"Topic":"TOP28","Name":"Z1_Cool_Request_Temp","Value":0,"Description":"&deg;C"},{"Topic":"TOP29","Name":"Z1_Heat_Curve_Target_High_Temp","Value":34,"Description":"&deg;C"},{"Topic":"TOP30","Name":"Z1_Heat_Curve_Target_Low_Temp","Value":30,"Description":"&deg;C"},{"Topic":"TOP31","Name":"Z1_Heat_Curve_Outside_High_Temp","Value":5,"Description":"&deg;C"},{"Topic":"TOP32","Name":"Z1_Heat_Curve_Outside_Low_Temp","Value":-15,"Description":"&deg;C"},{"Topic":"TOP33","Name":"Room_Thermostat_Temp","Value":23,"Description":"&deg;C"},{"Topic":"TOP34","Name":"Z2_Heat_Request_Temp","Value":0,"Description":"&deg;C"},{"Topic":"TOP35","Name":"Z2_Cool_Request_Temp","Value":0,"Description":"&deg;C"},{"Topic":"TOP36","Name":"Z1_Water_Temp","Value":22,"Description":"&deg;C"},{"Topic":"TOP37","Name":"Z2_Water_Temp","Value":24,"Description":"&deg;C"},{"Topic":"TOP38","Name":"Cool_Power_Production","Value":0,"Description":"Watt"},{"Topic":"TOP39","Name":"Cool_Power_Consumption","Value":0,"Description":"Watt"},{"Topic":"TOP40","Name":"DHW_Power_Production","Value":0,"Description":"Watt"},{"Topic":"TOP41","Name":"DHW_Power_Consumption","Value":0,"Description":"Watt"},{"Topic":"TOP42","Name":"Z1_Water_Target_Temp","Value":30,"Description":"&deg;C"},{"Topic":"TOP43","Name":"Z2_Water_Target_Temp","Value":32,"Description":"&deg;C"},{"Topic":"TOP44","Name":"Error","Value":"No error","Description":"Error"},{"Topic":"TOP45","Name":"Room_Holiday_Shift_Temp","Value":-15,"Description":"K"},{"Topic":"TOP46","Name":"Buffer_Temp","Value":-78,"Description":"&deg;C"},{"Topic":"TOP47","Name":"Solar_Temp","Value":-78,"Description":"&deg;C"},{"Topic":"TOP48","Name":"Pool_Temp","Value":-78,"Description":"&deg;C"},{"Topic":"TOP49","Name":"Main_Hex_Outlet_Temp","Value":23,"Description":"&deg;C"},{"Topic":"TOP50","Name":"Discharge_Temp","Value":9,"Description":"&deg;C"},{"Topic":"TOP51","Name":"Inside_Pipe_Temp","Value":23,"Description":"&deg;C"},{"Topic":"TOP52","Name":"Defrost_Temp","Value":12,"Description":"&deg;C"},{"Topic":"TOP53","Name":"Eva_Outlet_Temp","Value":12,"Description":"&deg;C"},{"Topic":"TOP54","Name":"Bypass_Outlet_Temp","Value":11,"Description":"&deg;C"},{"Topic":"TOP55","Name":"Ipm_Temp","Value":14,"Description":"&deg;C"},{"Topic":"TOP56","Name":"Z1_Temp","Value":22,"Description":"&deg;C"},{"Topic":"TOP57","Name":"Z2_Temp","Value":24,"Description":"&deg;C"},{"Topic":"TOP58","Name":"DHW_Heater_State","Value":1,"Description":"Free"},{"Topic":"TOP59","Name":"Room_Heater_State","Value":1,"Description":"Free"},{"Topic":"TOP60","Name":"Internal_Heater_State","Value":0,"Description":"Inactive"},{"Topic":"TOP61","Name":"External_Heater_State","Value":0,"Description":"Inactive"},{"Topic":"TOP62","Name":"Fan1_Motor_Speed","Value":0,"Description":"r/min"},{"Topic":"TOP63","Name":"Fan2_Motor_Speed","Value":0,"Description":"r/min"},{"Topic":"TOP64","Name":"High_Pressure","Value":11.0,"Description":"Kgf/cm2"},{"Topic":"TOP65","Name":"Pump_Speed","Value":0,"Description":"r/min"},{"Topic":"TOP66","Name":"Low_Pressure","Value":0,"Description":"Kgf/cm2"},{"Topic":"TOP67","Name":"Compressor_Current","Value":0.0,"Description":"Ampere"},{"Topic":"TOP68","Name":"Force_Heater_State","Value":0,"Description":"Inactive"},{"Topic":"TOP69","Name":"Sterilization_State","Value":0,"Description":"Inactive"},{"Topic":"TOP70","Name":"Sterilization_Temp","Value":65,"Description":"&deg;C"},{"Topic":"TOP71","Name":"Sterilization_Max_Time","Value":15,"Description":"Minutes"},{"Topic":"TOP72","Name":"Z1_Cool_Curve_Target_High_Temp","Value":16,"Description":"&deg;C"},{"Topic":"TOP73","Name":"Z1_Cool_Curve_Target_Low_Temp","Value":16,"Description":"&deg;C"},{"Topic":"TOP74","Name":"Z1_Cool_Curve_Outside_High_Temp","Value":30,"Description":"&deg;C"},{"Topic":"TOP75","Name":"Z1_Cool_Curve_Outside_Low_Temp","Value":20,"Description":"&deg;C"},{"Topic":"TOP76","Name":"Heating_Mode","Value":0,"Description":"Comp. Curve"},{"Topic":"TOP77","Name":"Heating_Off_Outdoor_Temp","Value":15,"Description":"&deg;C"},{"Topic":"TOP78","Name":"Heater_On_Outdoor_Temp","Value":-15,"Description":"&deg;C"},{"Topic":"TOP79","Name":"Heat_To_Cool_Temp","Value":15,"Description":"&deg;C"},{"Topic":"TOP80","Name":"Cool_To_Heat_Temp","Value":10,"Description":"&deg;C"},{"Topic":"TOP81","Name":"Cooling_Mode","Value":0,"Description":"Comp. Curve"},{"Topic":"TOP82","Name":"Z2_Heat_Curve_Target_High_Temp","Value":35,"Description":"&deg;C"},{"Topic":"TOP83","Name":"Z2_Heat_Curve_Target_Low_Temp","Value":32,"Description":"&deg;C"},{"Topic":"TOP84","Name":"Z2_Heat_Curve_Outside_High_Temp","Value":5,"Description":"&deg;C"},{"Topic":"TOP85","Name":"Z2_Heat_Curve_Outside_Low_Temp","Value":-15,"Description":"&deg;C"},{"Topic":"TOP86","Name":"Z2_Cool_Curve_Target_High_Temp","Value":16,"Description":"&deg;C"},{"Topic":"TOP87","Name":"Z2_Cool_Curve_Target_Low_Temp","Value":16,"Description":"&deg;C"},{"Topic":"TOP88","Name":"Z2_Cool_Curve_Outside_High_Temp","Value":30,"Description":"&deg;C"},{"Topic":"TOP89","Name":"Z2_Cool_Curve_Outside_Low_Temp","Value":20,"Description":"&deg;C"},{"Topic":"TOP90","Name":"Room_Heater_Operations_Hours","Value":41,"Description":"hours"},{"Topic":"TOP91","Name":"DHW_Heater_Operations_Hours","Value":33,"Description":"hours"},{"Topic":"TOP92","Name":"Heat_Pump_Model","Value":5,"Description":"IDU:WH-SXC12H9E8, ODU:WH-UX12HE8"},{"Topic":"TOP93","Name":"Pump_Duty","Value":0,"Description":"Duty"},{"Topic":"TOP94","Name":"Zones_State","Value":2,"Description":"Zone1 and zone2 active"},{"Topic":"TOP95","Name":"Max_Pump_Duty","Value":80,"Description":"Duty"},{"Topic":"TOP96","Name":"Heater_Delay_Time","Value":-1,"Description":"Minutes"},{"Topic":"TOP97","Name":"Heater_Start_Delta","Value":-128,"Description":"K"},{"Topic":"TOP98","Name":"Heater_Stop_Delta","Value":-128,"Description":"K"},{"Topic":"TOP99","Name":"Buffer_Installed","Value":0,"Description":"Disabled"},{"Topic":"TOP100","Name":"DHW_Installed","Value":1,"Description":"Enabled"},{"Topic":"TOP101","Name":"Solar_Mode","Value":0,"Description":"Disabled"},{"Topic":"TOP102","Name":"Solar_On_Delta","Value":10,"Description":"K"},{"Topic":"TOP103","Name":"Solar_Off_Delta","Value":5,"Description":"K"},{"Topic":"TOP104","Name":"Solar_Frost_Protection","Value":5,"Description":"&deg;C"},{"Topic":"TOP105","Name":"Solar_High_Limit","Value":80,"Description":"&deg;C"},{"Topic":"TOP106","Name":"Pump_Flowrate_Mode","Value":-1,"Description":"unknown"},{"Topic":"TOP107","Name":"Liquid_Type","Value":0,"Description":"Water"},{"Topic":"TOP108","Name":"Alt_External_Sensor","Value":0,"Description":"Disabled"},{"Topic":"TOP109","Name":"Anti_Freeze_Mode","Value":1,"Description":"Enabled"},{"Topic":"TOP110","Name":"Optional_PCB","Value":1,"Description":"Enabled"},{"Topic":"TOP111","Name":"Z1_Sensor_Settings","Value":1,"Description":"External Thermostat"},{"Topic":"TOP112","Name":"Z2_Sensor_Settings","Value":1,"Description":"External Thermostat"},{"Topic":"TOP113","Name":"Buffer_Tank_Delta","Value":0,"Description":"K"},{"Topic":"TOP114","Name":"External_Pad_Heater","Value":0,"Description":"Disabled"},{"Topic":"TOP115","Name":"Water_Pressure","Value":-0.02,"Description":"Bar"},{"Topic":"TOP116","Name":"Second_Inlet_Temp","Value":-128,"Description":"&deg;C"},{"Topic":"TOP117","Name":"Economizer_Outlet_Temp","Value":-128,"Description":"&deg;C"},{"Topic":"TOP118","Name":"Second_Room_Thermostat_Temp","Value":-128,"Description":"&deg;C"}],"1wire":[{"Sensor":"28aadd79a200035f","Temperature":20.94,"Alias":"Z1 Water "},{"Sensor":"288de579a2160390","Temperature":21.63,"Alias":"Inlet"},{"Sensor":"286d1479a21603d2","Temperature":21.94,"Alias":"Outlet"},{"Sensor":"289d3107d6013c3b","Temperature":21.38,"Alias":"Z2 Water "}]}`

**Comment by IgorYbema** [comment]
Can you check if, when the rules stops, the 'stats' line says that rules are disabled? ( Rules active: 0) Maybe it got rebooted (crash) and therefore disabled the rules.

For the '{}' issue, I can't see why. Are your sure these values aren't written by another mqtt client?

**Comment by MiG-41** [comment]
Ok , next time i'll veryfy "stats" , when rules stops ( but till now works).

Regarding {} , now for tests i changed MQTT Topic base , so Heishamon publishing to the new place ( and doupt that in this new place also some other client changing this value) , and the same...
image

Also i noticed , that instead of value , there is text "Decoded SparkplugB" in MQTT Explorer...

**Comment by MiG-41** [comment]
So after 6h work i noticed , that  "rules active" is now 0 ( before was 2).

Not sure ,if temperatures Z1 Water and Z2 Water are still updating ( since sensors are measuring water on pipes and they are under insulation. To change water temp need to do heating...

**Comment by IgorYbema** [comment]
Did the uptime change also?

**Comment by MiG-41** [comment]
so uptime in stats should freeze ?  It is linear since MQTT Explorer started , so should be updated...
image

**Comment by IgorYbema** [comment]
I mean, is the uptime much lower than expected so it can be true that a crash/reset has occured?

**Comment by MiG-41** [comment]
Uptime 7hours 8minutes ,  could be ,that around 1pm it done some restart , since i made some reboot before noon .... But this is not 100% sure :)

**Comment by IgorYbema** [comment]
Ok so not sure if the rules=0 started after the reboot (uptime=0)?

And no, I don't see weird values in mqtt. Also that Sparkplug8 is nothing what is in code of heishamon so should be some external mqtt client pushing that.

**Comment by IgorYbema** [comment]
Please, if you can, set the setting mqtt logging enabled and then dump all the /log topic to a text file while running. And then when you notice it has crashed or set rules to 0 again, stop the logging and send me the log file (can be hours of logging!)

**Comment by MiG-41** [comment]
Looks like this {} messages reads only MQTT Explorer 0.4.0-beta4 running on uBuntu !
MQTT-Explorer 0.4.0-beta1 on Windows reads this normally as values.... So it is a buq of MQTT Explorer...

**Comment by stumbaumr** [comment]
Means you still should enable logging to MQTT to find the reason for the reboot which then disables the rules.

**Comment by MiG-41** [comment]
Sure ,i'm doing it .. log without HEXdump is enough ?

**Comment by IgorYbema** [comment]
> Sure ,i'm doing it .. log without HEXdump is enough ?

Yes

**Comment by stumbaumr** [comment]
@IgorYbema , you should include https://github.com/IgorYbema/HeishaMon/pull/133 in the V3.5 release, otherwise the documentation is incomplete...

Almost 4 days uptime now the the #121 build - by never looking at the HeishaMon WebUI...

**Comment by MiG-41** [comment]
Whole night and it is still Rules active: 2 .... Maybe log have to be enabled all the time :)

**Comment by stumbaumr** [comment]
Or... did you have a browser window connected to the HeishaMon WebGUI at the time of the reboot?
See https://github.com/IgorYbema/HeishaMon/pull/121#issuecomment-2107095155

**Comment by IgorYbema** [comment]
I also had a reset yesterday when I had the browser open and switching between tabs. Need to figure this out but 3.5 is already installed on some shipped new heishamon so I'll go on and publish this release first.

**Comment by MiG-41** [comment]
From my side  i also stopped saving logs ( but they are still enabled and passing to mqtt) , since till now 3days and they are still run...

**Comment by klausj1** [comment]
> I also had a reset yesterday when I had the browser open and switching between tabs. Need to figure this out but 3.5 is already installed on some shipped new heishamon so I'll go on and publish this release first.

Hi @IgorYbema, are above mentioned "shipped new heishamon" available? According to [Tindie shop](https://www.tindie.com/products/thehognl/heishamon-communication-pcb/) they are out of stock, is there another place? Anyhow, I joined the waitlist

**Comment by stumbaumr** [comment]
Without using the WebUI currently works great!
image

**Pull request merged**
