### PR TITLE
Expose board type via mqtt

### PR DESCRIPTION
**Pull request by kamaradclimber**
This will help with https://github.com/kamaradclimber/heishamon-homeassistant/issues/248#issuecomment-2345404332

### CODE REVIEW

**Comment by kamaradclimber** [comment]
@IgorYbema do you have feedback on this?

**Comment by IgorYbema** [comment]
Is much easier to change. The stats line is already different for the ESP8266 and ESP32 so you can insert a simpel identifier for the board type there.

**Comment by kamaradclimber** [comment]
Good feedback, thanks! I've pushed a new version, let me know if this sounds better.

**Comment by IgorYbema** [comment]
Better. I think we can skip the unknown and default to ESP32 if it is not ESP8266 (like most of the other code)

**Comment by kamaradclimber** [comment]
Perfect, done!

**Pull request merged**
